#:schema node_modules/wrangler/config-schema.json
name = "storage"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

# Deploy an R2 bucket from the Cloudflare dashboard and fill in bucket_name.
[[r2_buckets]]
binding = 'R2'
bucket_name = ''

# KEY is required but can be set to any secret string.
[vars]
AUTH_KEY = ''